# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a79ad80e011ea718e5385d10df7f4eb6aa83db636f0ae5489fb501a6791b57b040ce3c683e499162a58f32dd5cd14495dc87c9962c3148676a5118747e6a30ec

test:
  secret_key_base: fe65a1322d78e5728426d0e00498d6807646b8944ed03f1a4f6aed90b0318a1c6c55228699d922f83445e306b7a43b4df617ab351cc8c4ded4dd154ce3969bc9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
